network_interface_name: eth0
network_connection_name: static-eth0
network_ip_address: 192.0.2.10
network_prefix: 24
network_gateway: 192.0.2.1
network_dns_servers:
  - 1.1.1.1
  - 8.8.8.8
network_dns_search: []
network_autoconnect: true
