---
- name: Write SNMP Exporter configuration
  ansible.builtin.template:
    src: "{{ snmp_exporter_paths.config_template }}"
    dest: "{{ snmp_exporter_paths.config }}"
    owner: "{{ snmp_exporter_service.user }}"
    group: "{{ snmp_exporter_service.group }}"
    mode: "0644"
  notify:
    - Reload systemd
    - Restart SNMP Exporter
  become: true

- name: Write SNMP Exporter systemd unit
  ansible.builtin.template:
    src: snmp_exporter.service.j2
    dest: "{{ snmp_exporter_paths.service_unit }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart SNMP Exporter
  become: true

- name: Ensure SNMP Exporter service state
  ansible.builtin.service:
    name: "{{ snmp_exporter_service.name }}"
    state: "{{ snmp_exporter_service.state }}"
    enabled: "{{ snmp_exporter_service.enabled }}"
  become: true
