---

- name: Write Loki configuration
  ansible.builtin.template:
    src: "{{ loki_paths.config_template }}"
    dest: "{{ loki_paths.config }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Loki
  become: true

- name: Write Loki systemd unit
  ansible.builtin.template:
    src: loki.service.j2
    dest: "{{ loki_paths.service_unit }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Loki
  become: true

- name: Ensure Loki service state
  ansible.builtin.service:
    name: "{{ loki_service.name }}"
    state: "{{ loki_service.state }}"
    enabled: "{{ loki_service.enabled }}"
  become: true
