---
- name: Install Alloy
  ansible.builtin.include_tasks:
    file: install.yaml
  when: alloy_enabled | bool

- name: Configure Alloy
  ansible.builtin.include_tasks:
    file: config.yaml
  when: alloy_enabled | bool
