---

- name: Write Promtail configuration
  ansible.builtin.template:
    src: "{{ promtail_paths.config_template }}"
    dest: "{{ promtail_paths.config }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Promtail
  become: true

- name: Write Promtail systemd unit
  ansible.builtin.template:
    src: promtail.service.j2
    dest: "{{ promtail_paths.service_unit }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Promtail
  become: true

- name: Ensure Promtail service state
  ansible.builtin.service:
    name: "{{ promtail_service.name }}"
    state: "{{ promtail_service.state }}"
    enabled: "{{ promtail_service.enabled }}"
  become: true
