---

- name: Install Promtail
  ansible.builtin.include_tasks:
    file: install.yaml
  when: promtail_enabled | bool

- name: Configure Promtail
  ansible.builtin.include_tasks:
    file: config.yaml
  when: promtail_enabled | bool
