---
# Install SteamCMD and CS2 server
- name: Tester SteamCMD sous l'utilisateur steam
  ansible.builtin.command:
    cmd: /usr/games/steamcmd +quit
  become: true
  become_user: steam
  environment:
    PATH: "/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  changed_when: false


- name: Afficher l'état initial
  ansible.builtin.debug:
    msg: "Begin of installation of CS2 with SteamCMD..."

- name: se connecter dans SteamCMD et installer CS2 # required. Full name of the interface excluding any logical unit number, i.e. Ethernet1/3.
  ansible.builtin.command:
    cmd: >
      /usr/games/steamcmd +login anonymous +force_install_dir /home/steam/cs2_server +app_update 730 validate +quit
  #args:
  # chdir: /home/steam
  become: true
  become_user: steam
  environment:
    PATH: "/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Afficher l'état final
  ansible.builtin.debug:
    msg: "The download and installation of CS2 with SteamCMD is complete."

- name: Vérifier l'installation de cs2
  ansible.builtin.command:
    cmd: >
      /usr/games/steamcmd +login anonymous +force_install_dir /home/steam/cs2_server +app_update 730 validate +quit
  args:
    chdir: /home/steam/cs2_server
  become: true
  become_user: steam
  environment:
    PATH: "/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  tags: steam

- name: Check if original and backup steamclient files exist
  ansible.builtin.stat:
    path: "{{ item }}"
  register: steam_files
  loop:
    - /home/steam/.steam/sdk64/steamclient.so
    - /home/steam/.steam/sdk64/steamclient.so.bak
  become: true

- name: Rename steamclient.so to steamclient.so.bak
  ansible.builtin.command:
    cmd: mv /home/steam/.steam/sdk64/steamclient.so /home/steam/.steam/sdk64/steamclient.so.bak
    removes: /home/steam/.steam/sdk64/steamclient.so
    creates: /home/steam/.steam/sdk64/steamclient.so.bak
  when:
    - steam_files.results[0].stat.exists
    - not steam_files.results[1].stat.exists
  become: true

- name: Ensure sdk64 directory exists
  ansible.builtin.file:
    path: /home/steam/.steam/sdk64
    state: directory
    owner: steam
    group: steam
    mode: '0755'
  become: true

- name: Replace steamclient.so with updated version from steamcmd
  ansible.builtin.copy:
    src: /home/steam/.steam/steam/steamcmd/linux64/steamclient.so
    dest: /home/steam/.steam/sdk64/steamclient.so
    remote_src: true
    owner: steam
    group: steam
    mode: '0644'
  become: true
