---

- name: Make cs2.sh  executable
  ansible.builtin.file:
    path: /home/steam/cs2_server/game/cs2.sh
    owner: steam
    group: steam
    mode: "0755"
    state: file
  become: true

- name: Create CS2 Service
  ansible.builtin.template:
    src: cs2.service.j2
    dest: /etc/systemd/system/cs2.service
    mode: '0644'
  notify: Reload systemd + start CS2
  become: true

- name: Enable and start CS2 daemon
  ansible.builtin.systemd:
    name: cs2
    state: started
    enabled: true
    daemon_reload: true
  become: true
  tags: cs2
