---
install_docker_users:
install_docker_compose_source_type: none
install_docker_compose_content: ""
install_docker_compose_template_src: docker-compose.yml.j2
install_docker_compose_url: ""
install_docker_compose_filename: docker-compose.yml
install_docker_compose_owner: "{{ ansible_user | default(ansible_facts['user_id'] | default('root')) }}"
install_docker_compose_group: "{{ install_docker_compose_owner }}"
install_docker_compose_target_dir: "/home/{{ install_docker_compose_owner }}/ansible-docker-compose"
install_docker_compose_file_path: "{{ install_docker_compose_target_dir }}/{{ install_docker_compose_filename }}"

# Registry pull-through proxy
install_docker_registry_mirror_enabled: true
install_docker_registry_mirror_host: "10.150.0.100"

install_docker_registry_mirrors:
  - "https://{{ docker_registry_mirror_host }}:5000" # Docker Hub

install_docker_registry_insecure_registries:
  - "{{ docker_registry_mirror_host }}:5000"
  - "{{ docker_registry_mirror_host }}:5001"
  - "{{ docker_registry_mirror_host }}:5002"
  - "{{ docker_registry_mirror_host }}:5003"
