---
galaxy_info:
  author: "Louis Raymond <lraymond@lanets.ca>"
  description: >
    Rôle Ansible pour préparer ZFS sur Debian (APT, paquets) et créer
    un pool/datasets à partir d'une liste de disques
  company: "Cedille"
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.11"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - debian
    - zfs
    - storage

dependencies: []
