---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd

- name: Restart pnp-server
  ansible.builtin.service:
    name: "{{ pnp_server_backend.service_name }}"
    state: restarted
  listen: Restart pnp-server
