---

- name: Portchannel to distribution
  cisco.ios.ios_config:
    lines:
      - description PORTCHANNEL TO D1
      - switchport trunk encapsulation dot1q
      - switchport trunk allowed vlan {{ mgmt_vlan }}, {{ client_vlan }}, {{ admin_wifi_vlan }}
      - switchport mode trunk
    parents:
      - interface Port-channel1

- name: Access Interfaces
  loop: "{{ range(1, 49) | list }}"
  block:
    - name: Setting up VLAN
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/{{ item }}
            spanning_tree:
              portfast:
                disabled: false
            mode: access
            access:
              vlan: "{{ client_vlan }}"
    - name: Setting up port security
      cisco.ios.ios_config:
        lines:
          - switchport port-security maximum 2
          - switchport port-security violation restrict
          - switchport port-security aging time 5
          - switchport port-security aging type inactivity
          - switchport port-security
        parents:
          - interface GigabitEthernet0/{{ item }}

- name: Uplink Interfaces (4x1GB)
  loop: "{{ range(1, 5) | list }}"
  when: uplink_config == '4x1'
  block:
    - name: Setting up VLAN
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/{{ item }}
            mode: trunk
            trunk:
              encapsulation: dot1q
              allowed_vlans:
                - "{{ mgmt_vlan }}"
                - "{{ client_vlan }}"
                - "{{ admin_wifi_vlan }}"
    - name: Setting up channel-group
      cisco.ios.ios_config:
        lines:
          - channel-group 1 mode active
        parents:
          - interface GigabitEthernet1/{{ item }}

- name: Uplink Interfaces (1x10GB)
  when: uplink_config == '1x10'
  cisco.ios.ios_l2_interfaces:
    config:
      - name: TenGigabitEthernet1/1
        mode: trunk
        trunk:
          encapsulation: dot1q
          allowed_vlans:
            - "{{ mgmt_vlan }}"
            - "{{ client_vlan }}"
            - "{{ admin_wifi_vlan }}"

- name: Uplink Interfaces (2x10GB)
  loop: "{{ range(1, 3) | list }}"
  when: uplink_config == '2x10'
  block:
    - name: Setting up VLAN
      cisco.ios.ios_l2_interfaces:
        config:
          - name: TenGigabitEthernet1/{{ item }}
            mode: trunk
            trunk:
              encapsulation: dot1q
              allowed_vlans:
                - "{{ mgmt_vlan }}"
                - "{{ client_vlan }}"
                - "{{ admin_wifi_vlan }}"
    - name: Setting up channel-group
      cisco.ios.ios_config:
        lines:
          - channel-group 1 mode active
        parents:
          - interface TenGigabitEthernet1/{{ item }}
