namespace: "cedille"
name: "netservices"
description: "Collection de rôles Ansible pour gérer des services réseau"
version: "1.0.1"
readme: "./docs/README.md"
authors:
  - "Louis Raymond <lraymond@lanets.ca>"
dependencies: {}
license:
  - "GPL-3.0-or-later"
tags:
  - "dns"
  - "dhcp"
repository: "https://github.com/ClubCedille/AnsibleRoles.git"
