---

vm_proxmox_api:
  user: "root"
  password:
  host:

vm_id:
vm_name:
vm_proxmox_node:
vm_cpu_type: "host"
vm_cpu_cores: 2
vm_memory_mb: 4096

vm_net:
  bridge: "vmbr1" # Management bridge is vmbr0; trunk bridge is vmbr1
  vlan: 1
  ip:
  netmask:
  gateway:
  nameservers: "1.1.1.1,8.8.8.8"
  search_domain: "localdomain"

vm_user: localadmin
vm_password:

vm_onboot: true

vm_disk_image_path:
vm_disk_storage: "local-lvm"
vm_disk_format: "qcow2"
vm_disk_device: "virtio0"
vm_cloud_init_storage:

vm_delete_if_exists: false
vm_start_after_creation: true
