---
- name: Install BIND9
  ansible.builtin.include_tasks:
    file: install.yaml
  when: netservices_dns.enabled | bool

- name: Configure BIND9
  ansible.builtin.include_tasks:
    file: config.yaml
  when: netservices_dns.enabled | bool
