---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart Blackbox Exporter
  ansible.builtin.service:
    name: "{{ blackbox_exporter_service.name }}"
    state: restarted
  become: true
