namespace: "cedille"
name: "github"
description: "Collection de rôles Ansible pour déployer des runners GitHub Actions self-hosted"
version: "0.1.0"
readme: "./docs/README.md"
authors:
  - "Louis Raymond <lraymond@lanets.ca>"
dependencies: {}
license:
  - "GPL-3.0-or-later"
tags:
  - "github"
  - "ci"
  - "actions"
repository: "https://github.com/ClubCedille/AnsibleRoles.git"
