---
- name: Fix ownership of game directory before extracting
  ansible.builtin.file:
    path: "/home/steam/cs2_server/game/csgo"
    owner: steam
    group: steam
    recurse: true
  become: true
  become_user: root

- name: Ensure local download directory exists
  ansible.builtin.file:
    path: /tmp/ansible_cs2
    state: directory
    mode: "0755"
  delegate_to: localhost

- name: Download Metamod to control node
  ansible.builtin.get_url:
    url: "{{ cs2_metamod_url }}"
    dest: /tmp/ansible_cs2/mmsource.tar.gz
    timeout: 300
    force: yes
  delegate_to: localhost

- name: Upload Metamod archive to remote host
  ansible.builtin.copy:
    src: /tmp/ansible_cs2/mmsource.tar.gz
    dest: /home/steam/cs2_server/game/csgo/mmsource.tar.gz
    owner: steam
    group: steam
    mode: "0640"
  become: true

- name: Extract Metamod on remote host
  ansible.builtin.unarchive:
    src: /home/steam/cs2_server/game/csgo/mmsource.tar.gz
    dest: /home/steam/cs2_server/game/csgo/
    remote_src: true
    mode: "0770"
  become: true
  become_user: steam

- name: Remove remote Metamod archive
  ansible.builtin.file:
    path: /home/steam/cs2_server/game/csgo/mmsource.tar.gz
    state: absent
  become: true

- name: Download CSSSharp to control node
  ansible.builtin.get_url:
    url: "{{ cs2_csssharp_url }}"
    dest: /tmp/ansible_cs2/counterstrikesharp.zip
    timeout: 300
    force: yes
  delegate_to: localhost

- name: Upload CSSSharp archive to remote host
  ansible.builtin.copy:
    src: /tmp/ansible_cs2/counterstrikesharp.zip
    dest: /home/steam/cs2_server/game/csgo/counterstrikesharp.zip
    owner: steam
    group: steam
    mode: "0640"
  become: true

- name: Extract CSSSharp on remote host
  ansible.builtin.unarchive:
    src: /home/steam/cs2_server/game/csgo/counterstrikesharp.zip
    dest: /home/steam/cs2_server/game/csgo/
    remote_src: true
    mode: "0770"
  become: true
  become_user: steam

- name: Remove remote CSSSharp archive
  ansible.builtin.file:
    path: /home/steam/cs2_server/game/csgo/counterstrikesharp.zip
    state: absent
  become: true

- name: Download MatchZy to control node
  ansible.builtin.get_url:
    url: "{{ cs2_matchzy_url }}"
    dest: /tmp/ansible_cs2/MatchZy.zip
    timeout: 300
    force: yes
  delegate_to: localhost

- name: Upload MatchZy archive to remote host
  ansible.builtin.copy:
    src: /tmp/ansible_cs2/MatchZy.zip
    dest: /home/steam/cs2_server/game/csgo/MatchZy.zip
    owner: steam
    group: steam
    mode: "0640"
  become: true

- name: Extract MatchZy on remote host
  ansible.builtin.unarchive:
    src: /home/steam/cs2_server/game/csgo/MatchZy.zip
    dest: /home/steam/cs2_server/game/csgo/
    remote_src: true
    mode: "0770"
  become: true
  become_user: steam

- name: Remove remote MatchZy archive
  ansible.builtin.file:
    path: /home/steam/cs2_server/game/csgo/MatchZy.zip
    state: absent
  become: true

- name: Copy MatchZy contents using shell
  ansible.builtin.shell: cp -r /home/steam/cs2_server/game/csgo/MatchZy-1.4.21/* /home/steam/cs2_server/game/csgo/
  become: true
  become_user: steam

- name: Clean up the now-empty MatchZy-XXXX directory
  ansible.builtin.file:
    path: "/home/steam/cs2_server/game/csgo/MatchZy-1.4.21/"
    state: absent
  become: true
  become_user: steam

- name: Backup gameinfo.gi file
  ansible.builtin.copy:
    src: /home/steam/cs2_server/game/csgo/gameinfo.gi
    dest: /home/steam/cs2_server/game/csgo/gameinfo.gi.bak
    remote_src: True
    mode: "0770"
  become: true
  become_user: steam

- name: Update gameinfo.gi to add Metamod
  ansible.builtin.lineinfile:
    path: /home/steam/cs2_server/game/csgo/gameinfo.gi
    insertafter: 'Game_LowViolence\s*csgo_lv\s*\/\/\s*Perfect\s*World\s*content\s*override'
    line: "        Game csgo/addons/metamod"
    mode: "0770"
  become: true
  become_user: steam

- name: Ensure cfg directory exists
  ansible.builtin.file:
    path: /home/steam/cs2_server/game/csgo/cfg
    state: directory
    owner: steam
    group: steam
    mode: "0755"
  become: true
  become_user: steam

- name: Verify and correct about the sv_logecho
  ansible.builtin.lineinfile:
    path: /home/steam/cs2_server/game/csgo/cfg/server.cfg
    line: "sv_logecho 1"
    regexp: "^sv_logecho"
    create: yes
    owner: steam
    group: steam
    mode: "0644"
  become: true
  become_user: steam

- name: Verify and correct about the log on
  ansible.builtin.lineinfile:
    path: /home/steam/cs2_server/game/csgo/cfg/server.cfg
    line: "log on"
    regexp: "^log"
    create: yes
    owner: steam
    group: steam
    mode: "0644"
  become: true
  become_user: steam

- name: Remove local plugin archives directory
  ansible.builtin.file:
    path: /tmp/ansible_cs2
    state: absent
  delegate_to: localhost
