---
galaxy_info:
  author: ClubCedille
  description: Configure Nix pour utiliser le cache/substituter interne Cedille (BasicAuth via netrc-file)
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: GenericLinux
      versions:
        - all

dependencies: []
