---
- name: Install Garage binary
  ansible.builtin.include_tasks:
    file: install.yaml
    apply:
      become: true

- name: Configure Garage
  ansible.builtin.include_tasks:
    file: configure.yaml
    apply:
      become: true

- name: Install Garage service
  ansible.builtin.include_tasks:
    file: service.yaml
    apply:
      become: true
