---
- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true
  when: netservices_dhcp.install.update_cache | bool
  become: true

- name: Install Kea packages
  ansible.builtin.apt:
    name: "{{ netservices_dhcp.install.packages }}"
    state: "{{ netservices_dhcp.install.package_state }}"
  become: true
