---
galaxy_info:
  author: ClubCedille
  description: Configure dnf pour utiliser le cache/mirror interne Cedille (BasicAuth)
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
