---
- name: Deploy containerized GitHub Actions runner (nested dockerd)
  ansible.builtin.include_tasks: containerized.yaml
  when: github_runner_containerized

- name: Deploy bare-metal GitHub Actions runner
  ansible.builtin.include_tasks: bare_metal.yaml
  when: not github_runner_containerized
